name: sim
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.1.1
  country_code_picker: ^3.1.0
  pinput: ^5.0.0
  flutter_svg: ^2.0.14
  intl: ^0.19.0
  image_picker: ^1.1.2
  flutter_rating_stars: ^1.1.0
  font_awesome_flutter: ^10.8.0
  lottie: ^3.1.3  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
    
  assets:
    - assets/images/

